require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OpportunitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Opportunity. As you add validations to Opportunity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end


  describe "GET index" do
    it "assigns all opportunities as @opportunities" do
      opportunity = Opportunity.create! valid_attributes
      get :index
      assigns(:opportunities).should eq([opportunity])
    end
  end


  describe "GET show" do
    it "assigns the requested opportunity as @opportunity" do
      opportunity = Opportunity.create! valid_attributes
      get :show, :id => opportunity.id.to_s
      assigns(:opportunity).should eq(opportunity)
    end
  end

  describe "GET new" do
    it "assigns a new opportunity as @opportunity" do
      get :new
      assigns(:opportunity).should be_a_new(Opportunity)
    end
  end

  describe "GET edit" do
    it "assigns the requested opportunity as @opportunity" do
      opportunity = Opportunity.create! valid_attributes
      get :edit, :id => opportunity.id.to_s
      assigns(:opportunity).should eq(opportunity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Opportunity" do
        expect {
          post :create, :opportunity => valid_attributes
        }.to change(Opportunity, :count).by(1)
      end

      it "assigns a newly created opportunity as @opportunity" do
        post :create, :opportunity => valid_attributes
        assigns(:opportunity).should be_a(Opportunity)
        assigns(:opportunity).should be_persisted
      end

      it "redirects to the created opportunity" do
        post :create, :opportunity => valid_attributes
        response.should redirect_to(Opportunity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved opportunity as @opportunity" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opportunity.any_instance.stub(:save).and_return(false)
        post :create, :opportunity => {}
        assigns(:opportunity).should be_a_new(Opportunity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opportunity.any_instance.stub(:save).and_return(false)
        post :create, :opportunity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested opportunity" do
        opportunity = Opportunity.create! valid_attributes
        # Assuming there are no other opportunities in the database, this
        # specifies that the Opportunity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Opportunity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => opportunity.id, :opportunity => {'these' => 'params'}
      end

      it "assigns the requested opportunity as @opportunity" do
        opportunity = Opportunity.create! valid_attributes
        put :update, :id => opportunity.id, :opportunity => valid_attributes
        assigns(:opportunity).should eq(opportunity)
      end

      it "redirects to the opportunity" do
        opportunity = Opportunity.create! valid_attributes
        put :update, :id => opportunity.id, :opportunity => valid_attributes
        response.should redirect_to(opportunity)
      end
    end

    describe "with invalid params" do
      it "assigns the opportunity as @opportunity" do
        opportunity = Opportunity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opportunity.any_instance.stub(:save).and_return(false)
        put :update, :id => opportunity.id.to_s, :opportunity => {}
        assigns(:opportunity).should eq(opportunity)
      end

      it "re-renders the 'edit' template" do
        opportunity = Opportunity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opportunity.any_instance.stub(:save).and_return(false)
        put :update, :id => opportunity.id.to_s, :opportunity => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested opportunity" do
      opportunity = Opportunity.create! valid_attributes
      expect {
        delete :destroy, :id => opportunity.id.to_s
      }.to change(Opportunity, :count).by(-1)
    end

    it "redirects to the opportunities list" do
      opportunity = Opportunity.create! valid_attributes
      delete :destroy, :id => opportunity.id.to_s
      response.should redirect_to(opportunities_url)
    end
  end

end
