require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # UsersProject. As you add validations to UsersProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all users_projects as @users_projects" do
      users_project = UsersProject.create! valid_attributes
      get :index
      assigns(:users_projects).should eq([users_project])
    end
  end

  describe "GET show" do
    it "assigns the requested users_project as @users_project" do
      users_project = UsersProject.create! valid_attributes
      get :show, :id => users_project.id.to_s
      assigns(:users_project).should eq(users_project)
    end
  end

  describe "GET new" do
    it "assigns a new users_project as @users_project" do
      get :new
      assigns(:users_project).should be_a_new(UsersProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested users_project as @users_project" do
      users_project = UsersProject.create! valid_attributes
      get :edit, :id => users_project.id.to_s
      assigns(:users_project).should eq(users_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UsersProject" do
        expect {
          post :create, :users_project => valid_attributes
        }.to change(UsersProject, :count).by(1)
      end

      it "assigns a newly created users_project as @users_project" do
        post :create, :users_project => valid_attributes
        assigns(:users_project).should be_a(UsersProject)
        assigns(:users_project).should be_persisted
      end

      it "redirects to the created users_project" do
        post :create, :users_project => valid_attributes
        response.should redirect_to(UsersProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved users_project as @users_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersProject.any_instance.stub(:save).and_return(false)
        post :create, :users_project => {}
        assigns(:users_project).should be_a_new(UsersProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersProject.any_instance.stub(:save).and_return(false)
        post :create, :users_project => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested users_project" do
        users_project = UsersProject.create! valid_attributes
        # Assuming there are no other users_projects in the database, this
        # specifies that the UsersProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UsersProject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => users_project.id, :users_project => {'these' => 'params'}
      end

      it "assigns the requested users_project as @users_project" do
        users_project = UsersProject.create! valid_attributes
        put :update, :id => users_project.id, :users_project => valid_attributes
        assigns(:users_project).should eq(users_project)
      end

      it "redirects to the users_project" do
        users_project = UsersProject.create! valid_attributes
        put :update, :id => users_project.id, :users_project => valid_attributes
        response.should redirect_to(users_project)
      end
    end

    describe "with invalid params" do
      it "assigns the users_project as @users_project" do
        users_project = UsersProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersProject.any_instance.stub(:save).and_return(false)
        put :update, :id => users_project.id.to_s, :users_project => {}
        assigns(:users_project).should eq(users_project)
      end

      it "re-renders the 'edit' template" do
        users_project = UsersProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersProject.any_instance.stub(:save).and_return(false)
        put :update, :id => users_project.id.to_s, :users_project => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested users_project" do
      users_project = UsersProject.create! valid_attributes
      expect {
        delete :destroy, :id => users_project.id.to_s
      }.to change(UsersProject, :count).by(-1)
    end

    it "redirects to the users_projects list" do
      users_project = UsersProject.create! valid_attributes
      delete :destroy, :id => users_project.id.to_s
      response.should redirect_to(users_projects_url)
    end
  end

end
